name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.1)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Determine tag
        id: vars
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.tag }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
          fi

      - name: Check release notes file
        id: notes
        shell: bash
        run: |
          TAG="${{ steps.vars.outputs.tag }}"
          FILE="docs/releases/${TAG}.md"
          if [ -f "$FILE" ]; then
            echo "body_path=$FILE" >> "$GITHUB_OUTPUT"
          else
            echo "body_path=" >> "$GITHUB_OUTPUT"
          fi

      - name: Create release (with body file)
        if: steps.notes.outputs.body_path != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          body_path: ${{ steps.notes.outputs.body_path }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release (auto notes)
        if: steps.notes.outputs.body_path == ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: ${{ steps.vars.outputs.tag }}
          draft: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
